#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="peertube"

prepare_service
check_container_initialized
check_service_initialized init
liftoff

cd /app

transform_var file \
                    DB_HOST \
                    DB_PORT \
                    DB_USER \
                    DB_PASS \
                    DB_SUFFIX \
                    DB_NAME \
                    OBJECT_STORAGE_CREDENTIALS_ACCESS_KEY_ID \
                    OBJECT_STORAGE_CREDENTIALS_SECRET_ACCESS_KEY \
                    OPENTELEMETRY_METRICS_PROMETHEUS_EXPORTER_HOST \
                    OPENTELEMETRY_METRICS_PROMETHEUS_EXPORTER_PORT \
                    OPENTELEMETRY_TRACING_JAEGER_EXPORTER_ENDPOINT \
                    PEERTUBE_SECRET \
                    REDIS_HOST \
                    REDIS_PASS \
                    SMTP_HOST \
                    SMTP_USER \
                    SMTP_PASS \
                    SMTP_PORT \

export HOME=/tmp/
export NODE_ENV=production
export NODE_CONFIG_DIR=${CONFIG_PATH}
export PEERTUBE_LOCAL_CONFIG=${CONFIG_PATH}

case "${PEERTUBE_CONTAINER,,}" in
    production )
        peertube_exec="node dist/server"
    ;;
    * )
        peertube_exec="npm run dev"
    ;;
esac

print_start "Starting Peertube $(grep -o "ADD: PeerTube .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}')"
exec s6-setuidgid peertube ${peertube_exec}
